sudo: required
dist: trusty
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.17.0 # Ruby 2.3.x
  - jruby-9.2.0.0 # Ruby 2.5.x
notifications:
  email: false
script: xvfb-run bundle exec rake
env:
  global:
    - BUNDLE_JOBS=4
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
matrix:
  allow_failures:
    - gemfile: gemfiles/master.gemfile
gemfile:
  - Gemfile
  - gemfiles/2.3.gemfile
  - gemfiles/master.gemfile
before_install:
  - gem install bundler
install: bundle
